name: Secrets Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:- uses: actions/checkout@v2- name: Gittyleaksuses: gupy-io/gittyleaks-action@v0.1